const fakeData = [
  {
    name: "Push Day",
    href: "/workouts/Push Day",
    exercises: [
      {
        id: 192,
        uuid: "5da6340b-22ec-4c1b-a443-eef2f59f92f0",
        name: "Bench Press",
        exercise_base: 73,
        status: "2",
        description:
          "<p>Lay down on a bench, the bar should be directly above your eyes, the knees are somewhat angled and the feet are firmly on the floor. Concentrate, breath deeply and grab the bar more than shoulder wide. Bring it slowly down till it briefly touches your chest at the height of your nipples. Push the bar up.</p>\n<p>If you train with a high weight it is advisable to have a <em>spotter</em> that can help you up if you can't lift the weight on your own.</p>\n<p>With the width of the grip you can also control which part of the chest is trained more:</p>\n<ul>\n<li>wide grip: outer chest muscles</li>\n<li>narrow grip: inner chest muscles and triceps</li>\n</ul>",
        creation_date: "2013-08-11",
        category: 11,
        muscles: [4],
        muscles_secondary: [2, 5],
        equipment: [1, 8],
        language: 2,
        license: 1,
        license_author: "sistab2",
        variations: [192, 100, 101, 163, 210, 211, 270, 399],
      },
      { name: "rest" },
      {
        id: 97,
        uuid: "0ec76f5d-1311-4d6d-bf79-00fa17c3061a",
        name: "Benchpress Dumbbells",
        exercise_base: 75,
        status: "2",
        description:
          "<p>The movement is very similar to benchpressing with a barbell, however, the weight is brought down to the chest at a lower point.</p>\n<p>Hold two dumbbells and lay down on a bench. Hold the weights next to the chest, at the height of your nipples and press them up till the arms are stretched. Let the weight slowly and controlled down.</p>",
        creation_date: "2013-05-05",
        category: 11,
        muscles: [4],
        muscles_secondary: [2, 5],
        equipment: [8, 3],
        language: 2,
        license: 1,
        license_author: "wger.de",
        variations: [],
      },
      {
        id: 354,
        uuid: "6335de72-146f-4f38-886d-6b8a27db62ff",
        name: "Burpees",
        exercise_base: 132,
        status: "2",
        description:
          "<p>Jump, lay down on your chest, do a pushup then jump, repeat</p>",
        creation_date: "2015-11-01",
        category: 11,
        muscles: [],
        muscles_secondary: [],
        equipment: [],
        language: 2,
        license: 2,
        license_author: "er0355",
        variations: [],
      },
      {
        id: 100,
        uuid: "b72ae8d4-ede6-4480-8fc5-7b80e369f7ed",
        name: "Decline Bench Press Barbell",
        exercise_base: 185,
        status: "2",
        description:
          "<p>Lay down on a decline bench, the bar should be directly above your eyes, the knees are somewhat angled and the feet are firmly on the floor. Concentrate, breath deeply and grab the bar more than shoulder wide. Bring it slowly down till it briefly touches your chest at the height of your nipples. Push the bar up.</p>",
        creation_date: "2013-05-05",
        category: 11,
        muscles: [4],
        muscles_secondary: [],
        equipment: [1],
        language: 2,
        license: 1,
        license_author: "wger.de",
        variations: [192, 100, 101, 163, 210, 211, 270, 399],
      },
      {
        id: 781,
        uuid: "7191e015-0c60-4376-9be0-733b9754b7f8",
        name: "Dips",
        exercise_base: 194,
        status: "2",
        description:
          "A dip is an upper-body strength exercise. Narrow, shoulder-width dips primarily train the triceps, with major synergists being the anterior deltoid, the pectoralis muscles (sternal, clavicular, and minor), and the rhomboid muscles of the back (in that order).[1] Wide arm training places additional emphasis on the pectoral muscles, similar in respect to the way a wide grip bench press would focus more on the pectorals and less on the triceps.",
        creation_date: "2020-04-06",
        category: 11,
        muscles: [4, 5],
        muscles_secondary: [5],
        equipment: [7],
        language: 2,
        license: 3,
        license_author: "BFad07",
        variations: [],
      },
    ],
    imageSrc:
      "https://images.unsplash.com/photo-1598971457999-ca4ef48a9a71?ixid=MnwxMjA3fDB8MHxzZWFyY2h8MXx8cHVzaHVwfGVufDB8fDB8fA%3D%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=400&q=60",
    imageAlt: "Push Day Image",
  },
  {
    name: "Pull Day",
    href: "/workouts/Pull Day",
    exercises: [
      {
        id: 412,
        uuid: "b8466ace-ebc7-42bb-941c-39e0e7e67a4f",
        name: "Bent Over Barbell Row",
        exercise_base: 80,
        status: "2",
        description:
          "<ol>\n<li>Holding a barbell with a pronated grip (palms facing down), bend your knees slightly and bring your torso forward, by bending at the waist, while keeping the back straight until it is almost parallel to the floor. Tip: Make sure that you keep the head up. The barbell should hang directly in front of you as your arms hang perpendicular to the floor and your torso. This is your starting position.</li>\n<li>Now, while keeping the torso stationary, breathe out and lift the barbell to you. Keep the elbows close to the body and only use the forearms to hold the weight. At the top contracted position, squeeze the back muscles and hold for a brief pause.</li>\n<li>Then inhale and slowly lower the barbell back to the starting position.</li>\n<li>Repeat for the recommended amount of repetitions.</li>\n</ol>",
        creation_date: "2016-08-15",
        category: 12,
        muscles: [],
        muscles_secondary: [],
        equipment: [1],
        language: 2,
        license: 2,
        license_author: "warchildmd",
        variations: [
          412, 362, 109, 110, 340, 214, 202, 670, 142, 108, 106, 339,
        ],
      },
      {
        id: 803,
        uuid: "0849d95d-e83b-44bd-ae95-1fcb89fa5a04",
        name: "Chin Up",
        exercise_base: 152,
        status: "2",
        description:
          "The chin-up (also known as a chin or chinup) is a strength training exercise. People frequently do this exercise with the intention of strengthening muscles such as the latissimus dorsi and biceps, which extend the shoulder and flex the elbow, respectively. In this maneuver, the palms are faced towards the body. It is a form of pull-up in which the range of motion is established in relation to a person's chin.",
        creation_date: "2020-05-10",
        category: 12,
        muscles: [],
        muscles_secondary: [],
        equipment: [6],
        language: 2,
        license: 3,
        license_author: "BFad07",
        variations: [],
      },
      {
        id: 213,
        uuid: "42b092ec-80b1-4471-90d1-e462a65ab18c",
        name: "Close-grip Lat Pull Down",
        exercise_base: 158,
        status: "2",
        description:
          "<p>Grip the pull-down bar with your hands closer than shoulder width apart, with your palms facing away from you. Lean back slightly. Pull the bar down towards your chest, keeping your elbows close to your sides as you come down. Pull your shoulders back at the end of the motion.</p>",
        creation_date: "2014-02-01",
        category: 12,
        muscles: [12],
        muscles_secondary: [],
        equipment: [],
        language: 2,
        license: 1,
        license_author: "tuckerm",
        variations: [213, 188, 187, 216, 215, 212, 424, 204],
      },
      {
        id: 105,
        uuid: "22cca8fc-cfaf-4941-b0f7-faf9f2937c52",
        name: "Deadlifts",
        exercise_base: 184,
        status: "2",
        description:
          "<p>Stand firmly, with your feet slightly more than shoulder wide apart. Stand directly behind the bar where it should barely touch your shin, your feet pointing a bit out. Bend down with a straight back, the knees also pointing somewhat out. Grab the bar with a shoulder wide grip, one underhand, one reverse grip.</p>\n<p>Pull the weight up. At the highest point make a slight hollow back and pull the bar back. Hold 1 or 2 seconds that position. Go down, making sure the back is not bent. Once down you can either go back again as soon as the weights touch the floor, or make a pause, depending on the weight.</p>",
        creation_date: "2013-05-05",
        category: 12,
        muscles: [12, 10],
        muscles_secondary: [8],
        equipment: [1],
        language: 2,
        license: 1,
        license_author: "wger.de",
        variations: [105, 381, 161, 351, 328, 209],
      },
    ],
    imageSrc:
      "https://images.unsplash.com/photo-1615544983150-0760f39857f5?ixid=MnwxMjA3fDB8MHxzZWFyY2h8MTN8fHB1bGwlMjB1cHxlbnwwfHwwfHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=400&q=60",
    imageAlt: "Pull Day Image",
  },
  {
    name: "Leg Day",
    href: "/workouts/Leg Day",
    exercises: [
      {
        id: 405,
        uuid: "ae6a6c23-4616-49b7-a152-49d7461c2b7f",
        name: "Barbell Lunges",
        exercise_base: 46,
        status: "2",
        description:
          "<p>Put barbell on the back of your shoulders. Stand upright, then take the first step forward. Step should bring you forward so that your supporting legs knee can touch the floor. Then stand back up and repeat with the other leg.</p>\n<p>Remember to keep good posture.</p>",
        creation_date: "2016-07-30",
        category: 9,
        muscles: [10],
        muscles_secondary: [8],
        equipment: [1],
        language: 2,
        license: 2,
        license_author: "Mikko Ruohola",
        variations: [405, 112, 113],
      },
      {
        id: 914,
        uuid: "a9f2d62a-6a3c-4b20-b3ff-cb3654bf3195",
        name: "Bulgarian Split Squat",
        exercise_base: 748,
        status: "2",
        description:
          "<p>1. Find a stable implement (a bench or a chair) and place the left foot hip-distance in front of the right one. Your core should be engaged, your shoulders should be back and your eyes and chest should face forward.</p>\n<p>2. Raise the right leg off the ground and pulace it on the bench behind you.</p>\n<p>3. Check your balance and distance between the feet. Your feet should not be on the same line as that will make it difficult to balance.</p>\n<p>4. Bend your left knee and lower downard. Maintain position and push upward. The right knee is used only for balance and should bend by itself.</p>\n<p>5. Switch the feet and repeat</p>\n<p>The exercise can be done without weights, with dumbbells or a barbell.</p>",
        creation_date: "2021-07-29",
        category: 9,
        muscles: [10],
        muscles_secondary: [11, 8],
        equipment: [1, 8, 3, 7],
        language: 2,
        license: 2,
        license_author: "hanswolo",
        variations: [],
      },
      {
        id: 408,
        uuid: "97ae7d90-a4b2-472c-bf7b-826df674622c",
        name: "Glute Bridge",
        exercise_base: 265,
        status: "2",
        description:
          "<p>Lie on you back with your hips and knees flexed, feet on the ground. From this position, raise your butt off of the ground to a height where your body makes a straight line from your knees to your shoulders. To make the exercise more intense, you can add weight by letting a barbell rest on your hips as you complete the motion, or you can put your feet on a slightly higher surface such as a step or a bench.</p>",
        creation_date: "2016-07-31",
        category: 9,
        muscles: [8],
        muscles_secondary: [11],
        equipment: [],
        language: 2,
        license: 2,
        license_author: "tdprice12",
        variations: [],
      },
      {
        id: 854,
        uuid: "37097633-de80-4271-9b7c-291f359e0ef4",
        name: "Hip Thrust",
        exercise_base: 294,
        status: "2",
        description:
          "<p>The bar should go directly on your upper thigh, directly below your crotch. Your feet should be directly under your knees. Push your hips up so that you form a straight line from your knees to your shoulders. Use a pad for comfort.</p>",
        creation_date: "2020-10-31",
        category: 9,
        muscles: [8],
        muscles_secondary: [],
        equipment: [1, 8],
        language: 2,
        license: 2,
        license_author: "Bret Contreras",
        variations: [],
      },
    ],
    imageSrc:
      "https://images.unsplash.com/flagged/photo-1566064336477-864e4f308992?ixid=MnwxMjA3fDB8MHxzZWFyY2h8M3x8c3F1YXR8ZW58MHx8MHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=400&q=60",
    imageAlt: "Leg Day Image",
  },
  {
    name: "Full Body Split",
    href: "/workouts/Full Body Split",
    exercises: [
      {
        id: 810,
        uuid: "75ab9694-63f2-4794-ae2f-e93abb2255b8",
        name: "Jumping Jacks",
        exercise_base: 320,
        status: "2",
        description:
          "<p>A jumping jack or star jump, also called side-straddle hop in the US military, is a physical jumping exercise performed by jumping to a position with the legs spread wide and the hands going overhead, sometimes in a clap, and then returning to a position with the feet together and the arms at the sides</p>",
        creation_date: "2020-05-28",
        category: 9,
        muscles: [10],
        muscles_secondary: [],
        equipment: [],
        language: 2,
        license: 2,
        license_author: "student1234",
        variations: [],
      },
      {
        id: 91,
        uuid: "d325dd5c-6833-41c7-8eea-6b95c4871133",
        name: "Crunches",
        exercise_base: 167,
        status: "2",
        description:
          "<p>Lay down on your back a soft surface, the feet are on the floor. Ask a partner or use some other help (barbell, etc.) to keep them fixed, your hands are behind your head. From this position move your upper body up till your head or elbows touch your knees. Do this movement by rolling up your back.</p>",
        creation_date: "2013-05-05",
        category: 10,
        muscles: [6],
        muscles_secondary: [3],
        equipment: [8, 4],
        language: 2,
        license: 1,
        license_author: "wger.de",
        variations: [91, 94, 92, 416, 93, 176, 95, 170],
      },
      {
        id: 303,
        uuid: "ce37341b-379c-4611-ac9f-830c6c3c397a",
        name: "Flutter Kicks",
        exercise_base: 235,
        status: "2",
        description:
          "<p>-Laying on the back, lift your straightened legs from the ground at a 45 degree angle. </p>\n<p>-As your Left foot travels downward and nearly touches the floor, your Right foot should seek to reach a 90 degree angle, or as close to one as possible.</p>\n<p>-Bring your R foot down until it nearly touches the floor, and bring your L foot upwards.  Maintain leg rigidity throughout the exercise.  Your head should stay off the ground, supported by tightened upper abdominals.</p>\n<p>-(L up R down, L down R up, x2)  ^v, v^, ^v, v^ = 1 rep</p>\n<p>-Primarily works the Rectus Abdominus, the hip flexors and the lower back. Secondarily works the Obliques.  Emphasis placed on the lower quadrant of the abs.</p>\n<p> </p>",
        creation_date: "2015-02-06",
        category: 10,
        muscles: [14, 6],
        muscles_secondary: [],
        equipment: [],
        language: 2,
        license: 2,
        license_author: "nate303303",
        variations: [303, 166, 125, 126, 631],
      },
      {
        id: 260,
        uuid: "36ef5f12-6f77-4754-a926-39915e4b57a5",
        name: "Decline Pushups",
        exercise_base: 188,
        status: "2",
        description:
          "<p>With your feet raised approximately 30cm on a platform, align your shoulders, elbows and hands, then perform regular pushups. This emphasises the clavicular fibers of the pectoralis major.</p>",
        creation_date: "2014-07-12",
        category: 11,
        muscles: [4],
        muscles_secondary: [2, 5],
        equipment: [7],
        language: 2,
        license: 1,
        license_author: "aszc",
        variations: [260, 168, 182, 790, 302],
      },
      {
        id: 107,
        uuid: "7ce6b090-5099-4cd0-83ae-1a02725c868b",
        name: "Pull-ups",
        exercise_base: 475,
        status: "2",
        description:
          "<p>Grab the pull up bar with a wide grip, the body is hanging freely. Keep your chest out and pull yourself up till your chin reaches the bar or it touches your neck, if you want to pull behind you. Go with a slow and controlled movement down, always keeping the chest out.</p>",
        creation_date: "2013-05-05",
        category: 12,
        muscles: [12],
        muscles_secondary: [2, 1, 9],
        equipment: [6],
        language: 2,
        license: 1,
        license_author: "wger.de",
        variations: [],
      },
      {
        id: 160,
        uuid: "b1d6d536-7f4a-4dd3-8b76-62d7a984e115",
        name: "Pistol Squat",
        exercise_base: 456,
        status: "2",
        description: "<p>One legged squat</p>",
        creation_date: "2013-05-28",
        category: 9,
        muscles: [11, 8],
        muscles_secondary: [2, 1, 13],
        equipment: [],
        language: 2,
        license: 1,
        license_author: "minifigmaster125",
        variations: [
          407, 342, 300, 191, 650, 389, 355, 160, 185, 111, 795, 387,
        ],
      },
    ],
    imageSrc:
      "https://images.unsplash.com/photo-1608217034924-9e8ef080aa5d?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1470&q=80",
    imageAlt: "Full Body Split Image",
  },
];

export default fakeData;
